config/routes.rb
Rails.application.routes.draw do
  root 'questions#index'

  concern :votable do
    member do
      get :upvote
      get :downvote
    end
  end

  resources :questions, concerns: [:votable] do
    resources :answers, concerns: [:votable]
  end

  get 'widget' => 'widget#index'
  post 'widget' => 'widget#ajax'

end

app/models/answer.rb
class Answer < ActiveRecord::Base
  belongs_to :question

  validates :title, :content, presence: true
end

app/models/question.rb
class Question < ActiveRecord::Base
  has_many :answers, dependent: :destroy

  validates :title, :content, presence: true
end

app/models/zen.rb
class Zen
  def initialize
    @request = HTTParty.get("https://api.github.com/zen?access_token=#{ENV['TOKEN']}", headers: { 'User-Agent' => "#{ENV['URL']}"})
  end

  def quote
    @request.body
  end
end

app/controllers/answers_controller.rb
class AnswersController < ApplicationController

  def index
    @question = Question.find(params[:question_id])
    p @answers = @question.answers
    @answer = @question.answers.new
  end

  def show
    @question = Question.find(params[:question_id])

    @answer = @question.answers.find(params[:id])
  end

  def new
    @question = Question.find(params[:question_id])

    @answer = @question.answers.new
  end

  def edit
    @question = Question.find(params[:question_id])

    @answer = @question.answers.find(params[:id])
  end

  def create
    @question = Question.find(params[:question_id])
    @answer = @question.answers.new(answer_params)

    @answer.save ? (redirect_to question_answers_path) : (render 'new')
  end

  def update
    @question = Question.find(params[:question_id])
    @answer = @question.answers.find(params[:id])

    @answer.save ? (redirect_to question_answers_path) : (render 'new')
  end

  def upvote
    @question = Question.find(params[:question_id])
    @answer = @question.answers.find(params[:id])
    @answer.increment!(:vote_total)
    redirect_to question_answers_path
  end

  def downvote
    @question = Question.find(params[:question_id])
    @answer = @question.answers.find(params[:id])
    @answer.decrement!(:vote_total)
    redirect_to question_answers_path
  end

  def delete
    # No delete feature yet
  end

  private
  def answer_params
    params.require(:answer).permit(:title, :content)
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController

  def index
    @questions = Question.all
    @question = Question.new
    @quote = Zen.new.quote
  end

  def show
    @question = Question.find(params[:id])
  end

  def new
    @question = Question.new
  end

  def edit
    @question = Question.find(params[:id])
  end

  def create
    @question = Question.new(question_params)

    @question.save ? (render :json => @question) : (render 'new')
  end

  def update
    @question = Question.find(params[:id])

    @question.update(question_params) ? (redirect_to questions_path) : (render 'edit')
  end

  def upvote
    @question = Question.find(params[:id])
    @question.increment!(:vote_total)
    render :json => @question
  end

  def downvote
    @question = Question.find(params[:id])
    @question.decrement!(:vote_total)
    render :json => @question
  end

  def destroy
    @question = Question.find(params[:id])
    @question.destroy
    render :index
  end


  private
  def question_params
    params.require(:question).permit(:title, :content)
  end

end

app/controllers/widget_controller.rb
class WidgetController < ApplicationController

  def index
    @widget = ''
  end

  def ajax
    @widget = { title: params[:title], content: params[:content] }
    render :json => @widget
  end
end

app/helpers/answer_helper.rb
module AnswerHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/question_helper.rb
module QuestionHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/helpers/widget_helper.rb
module WidgetHelper
end

app/helpers/zen_helper.rb
module ZenHelper
end

app/views/answers/_form.html.erb
<%= form_for @answer, url: question_answers_path do |f| %>

  <% if @answer.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@answer.errors.count, "error") %> prohibited
        this answer from being saved:
      </h2>
      <ul>
        <% @answer.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <p>
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </p>

  <p>
    <%= f.label :content %><br>
    <%= f.text_area :content %>
  </p>

  <p>
    <%= f.submit %>
  </p>

<% end %>

app/views/answers/index.html.erb
<div class="container">
  <div class="jumbotron">
    <h1><%= @question.title %></h1>
  </div>
  <div class="page-header">
    <h2><%= @question.content %></h2>
  </div>
  <%= image_tag('crab.png') %>
  <h2>Add Answer</h2>
  <%= render 'form' %>

  <button><%= link_to 'Back', questions_path %></button>

  <ul>
    <%= content_tag_for(:li, @answers[0..-2]) do |answer| %>
    <section>
      <h2><%= answer.title %></h2>
      <p><%= answer.content %></p>
      <h3>Votes: <%= answer.vote_total %></h3>
      <button><%= link_to 'Upvote!', "/questions/#{@question.id}/answers/#{answer.id}/upvote" %></button>
      <button><%= link_to 'Downvote!', "/questions/#{@question.id}/answers/#{answer.id}/downvote" %></button>
    </section>
    <% end %>
  </ul>
</div>

app/views/answers/new.html.erb
<h1>New Answer</h1>

<%= form_for @answer, url: question_answers_path do |f| %>

  <% if @answer.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@answer.errors.count, "error") %> prohibited
        this answer from being saved:
      </h2>
      <ul>
        <% @answer.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <p>
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </p>

  <p>
    <%= f.label :content %><br>
    <%= f.text_area :content %>
  </p>

  <p>
    <%= f.submit %>
  </p>

<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>DbcOverflow</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
</body>
</html>

app/views/questions/_form.html.erb
<div class="input-group">
<%= form_for @question, html: { role: "form" } do |f| %>

  <% if @question.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@question.errors.count, "error") %> prohibited
        this question from being saved:
      </h2>
      <ul>
        <% @question.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <p>
    <div class="form-group">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
    </div>
  </p>

  <p>
    <div class="form-group">
    <%= f.label :content %><br>
    <%= f.text_area :content %>
  </div>
  </p>

  <p>
    <%= f.submit %>
  </p>

<% end %>
</div>

app/views/questions/edit.html.erb
<h1>Edit <%= @question.title %></h1>

<%= form_for @question, url: question_path do |f| %>

  <% if @question.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@question.errors.count, "error") %> prohibited
        this question from being saved:
      </h2>
      <ul>
        <% @question.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <p>
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </p>

  <p>
    <%= f.label :content %><br>
    <%= f.text_area :content %>
  </p>

  <p>
    <%= f.submit %>
  </p>

<% end %>

app/views/questions/index.html.erb
<div class="container">
  <div class="jumbotron">
    <h1>DBC Overflow! <br><small><%= @quote %></small></h1>
  </div>

  <%= image_tag('crab.png', class: 'media-object') %>


  <h2>Ask Your Question</h2>

  <%= render 'form' %>

  <div class='question-template'>
    <ul>
      <%= content_tag_for(:li, @questions) do |question| %>
      <section class='<%= question.id  %>'>
        <h2><%= link_to question.title, question_answers_path(question) %></h2>
        <p><%= question.content %></p>
        <h3 class='vote-total'>Votes: <%= question.vote_total %></h3>
        <button class='upvote-trigger' data-url='<%= upvote_question_path(question) %>'><%= link_to 'Upvote!', '' %></button>
        <button class='downvote-trigger' data-url='<%= downvote_question_path(question) %>'><%= link_to 'Downvote!', '' %></button>
        <button><%= link_to 'Edit', edit_question_path(question) %></button>
        <button class='delete' data-id='<%= question.id  %>' data-url='<%= question_path(question) %>'><a>Delete</a></button>
        <% end %>
      </section>
    </ul>
  </div>
</div>

app/views/questions/show.html.erb
<h1><%= @question.title %></h1>

<p><%= @question.content %></p>

<h2>Your Question has been posted</h2>

<%= link_to 'Back', questions_path %>

app/views/widget/index.html.erb
<%= form_for @widget, url: widget_path, html: {:class => "widget"} do |f| %>

  <p>
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </p>

  <p>
    <%= f.label :content %><br>
    <%= f.text_area :content %>
  </p>

  <p>
    <%= f.submit %>
  </p>

<% end %>

<article class="markdown-container">

</article>